client_api_url:
code_repo: "https://github.com/Code-My-Spec/test_phoenix_project"
description:
docs_repo: "https://github.com/Code-My-Spec/test_phoenix_project_docs"
module_name: TestPhoenixProject
name: Test Phoenix Project
project_id: 12481677-31ee-4d1c-9c73-760aede5f048
account_id: 0f27281c-240b-4d6d-8e52-9c5972329522
